version: '3.8'

services:
  jobs:
    build:
      context: .
      dockerfile: Dockerfile.jobs
    container_name: news-jobs
    env_file:
      - .env
    environment:
      - NEWSDATA_API_KEY=${NEWSDATA_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GCS_BUCKET=${GCS_BUCKET}
      - GCS_PREFIX=${GCS_PREFIX:-news_data}
    entrypoint: ["bash", "run-jobs.sh"]
    restart: "no"

  dashboard:
    build:
      context: ./NewsAgent
      dockerfile: Dockerfile
    container_name: news-dashboard
    env_file:
      - .env
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GCS_BUCKET=${GCS_BUCKET}
    ports:
      - "8080:8080"
    command: ["bash", "NewsAgent/deploy.sh"]
    depends_on:
      - jobs
    restart: unless-stopped
